"""Regenerate the SQL seed, preserving the 7-table ERD.
Usage: python3 database/scripts/generate_seed.py /path/to/demo-hashes.json
The JSON must have bcrypt hashes under admin and user. No plaintext passwords
are generated by this script. Generated times/distances/capacities are demo data.
"""
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
hashes = json.loads(Path(sys.argv[1]).read_text())
for key in ('admin', 'user'):
    if not hashes[key].startswith(('$2a$', '$2b$', '$2y$')):
        raise ValueError('Expected bcrypt hashes')

def quote(v):
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"

# Selected landmarks along published Hanoi routes, NOT a complete stop registry.
stations = [
 ('HN-BC', 'Bác Cổ - Trần Khánh Dư', 'Khu vực Trần Khánh Dư, Hà Nội'),
 ('HN-TT', 'Tràng Thi', 'Phố Tràng Thi, Hà Nội'),
 ('HN-NTS', 'Ngã Tư Sở', 'Khu vực Tây Sơn - Nguyễn Trãi, Hà Nội'),
 ('HN-PTIT', 'Học viện Công nghệ Bưu chính Viễn thông', 'Trần Phú, Hà Đông, Hà Nội'),
 ('HN-YN', 'Bến xe Yên Nghĩa', 'Quốc lộ 6, khu vực Yên Nghĩa, Hà Nội'),
 ('HN-MD', 'Mai Động', 'Bãi đỗ xe Kim Ngưu I, Hà Nội'),
 ('HN-TN', 'Thanh Nhàn', 'Phố Thanh Nhàn, Hà Nội'),
 ('HN-CB', 'Chùa Bộc', 'Phố Chùa Bộc, Hà Nội'),
 ('HN-CG', 'Cầu Giấy', 'Đường Cầu Giấy, Hà Nội'),
 ('HN-SVD', 'Sân vận động Quốc gia Mỹ Đình', 'Khu vực Lê Đức Thọ, Hà Nội'),
 ('HN-KM', 'Kim Mã', 'Số 1 Kim Mã, Hà Nội'),
 ('HN-NT', 'Nhà chờ Núi Trúc', 'Khu vực Núi Trúc - Giảng Võ, Hà Nội'),
 ('HN-GV', 'Nhà chờ Giảng Võ', 'Đường Giảng Võ, Hà Nội'),
 ('HN-HDT', 'Nhà chờ Hoàng Đạo Thúy', 'Khu vực Hoàng Đạo Thúy - Lê Văn Lương, Hà Nội'),
 ('HN-TV', 'Nhà chờ Trung Văn', 'Đường Tố Hữu, khu vực Trung Văn, Hà Nội'),
 ('HN-VP2', 'Nhà chờ Vạn Phúc 2', 'Đường Tố Hữu, khu vực Vạn Phúc, Hà Nội'),
 ('HN-VP1', 'Nhà chờ Vạn Phúc 1', 'Đường Tố Hữu, khu vực Vạn Phúc, Hà Nội'),
 ('HN-VK', 'Nhà chờ Văn Khê', 'Đường Tố Hữu, khu vực Văn Khê, Hà Nội'),
 ('HN-CLK', 'Nhà chờ Cầu La Khê', 'Khu vực Cầu La Khê, Hà Nội'),
]
# Distance and minute offsets below are estimates for the coursework demo.
base_routes = [
 ('02', ['HN-BC','HN-TT','HN-NTS','HN-PTIT','HN-YN'], [0,2,7,12,20], [0,8,23,40,65]),
 ('26', ['HN-MD','HN-TN','HN-CB','HN-CG','HN-SVD'], [0,2,6,12,18], [0,8,22,42,60]),
 ('BRT01', ['HN-KM','HN-NT','HN-GV','HN-HDT','HN-TV','HN-VP2','HN-VP1','HN-VK','HN-CLK','HN-YN'],
  [0,0.8,1.6,4.6,7.6,9,9.6,11,12.6,15], [0,3,6,15,25,30,33,38,44,55]),
]
name_by_code = {c:n for c,n,_ in stations}
lines = [
 '-- Hanoi reference data; selected stops only. See database/README.md for sources.',
 '-- Names and route corridors: public Hanoi references.',
 '-- Km, offsets, operating hours, vehicle codes, capacity and dated schedules: DEMO.',
 '-- Fares follow the coursework formula, not official Hanoi fares.',
 '-- Seed is additive: existing records, prices, tickets and passwords are preserved.',
 "SET NAMES utf8mb4;", "SET time_zone = '+00:00';", 'USE gobus_hanoi_erd;', 'START TRANSACTION;',
]
for code,name,address in stations:
    lines.append('INSERT INTO stations(code,name,address) SELECT '+','.join(map(quote,(code,name,address)))+' WHERE NOT EXISTS (SELECT 1 FROM stations WHERE code='+quote(code)+');')
for email,name,role,h in [('admin@gobus.local','Quản trị viên GoBus','ADMIN',hashes['admin']),('an@gobus.local','Nguyễn Văn An (demo)','USER',hashes['user']),('binh@gobus.local','Trần Thị Bình (demo)','USER',hashes['user'])]:
    lines.append('INSERT INTO users(email,full_name,role,password_hash) SELECT '+','.join(map(quote,(email,name,role,h)))+' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='+quote(email)+');')
for code,stops,kms,mins in base_routes:
    for direction in ('DI','VE'):
        s = stops if direction=='DI' else list(reversed(stops))
        km = kms if direction=='DI' else [round(kms[-1]-v,2) for v in reversed(kms)]
        minute = mins if direction=='DI' else [mins[-1]-v for v in reversed(mins)]
        route_code=code+'-'+direction
        route_name=name_by_code[s[0]]+' → '+name_by_code[s[-1]]
        lines += [
          '\n-- Route '+route_code+'; direction modeled separately.',
          'INSERT INTO routes(code,name,origin_station_id,destination_station_id,operating_start,operating_end,distance_km)',
          'SELECT '+quote(route_code)+','+quote(route_name)+",a.id,z.id,'05:00:00','22:00:00',"+quote(km[-1])+' FROM stations a JOIN stations z ON z.code='+quote(s[-1])+' WHERE a.code='+quote(s[0])+' AND NOT EXISTS (SELECT 1 FROM routes WHERE code='+quote(route_code)+');',
          'SET @rid=(SELECT id FROM routes WHERE code='+quote(route_code)+');',
        ]
        for i,c in enumerate(s):
            lines.append('INSERT INTO route_stops(route_id,station_id,stop_order,minutes_from_origin,km_from_origin) SELECT @rid,id,'+','.join(map(quote,(i+1,minute[i],km[i])))+' FROM stations WHERE code='+quote(c)+' AND NOT EXISTS (SELECT 1 FROM route_stops WHERE route_id=@rid AND stop_order='+str(i+1)+');')
lines += [
 '\n-- All forward segments, per route direction. Round to nearest VND.',
 'INSERT INTO fares(route_id,from_station_id,to_station_id,price)',
 'SELECT a.route_id,a.station_id,z.station_id,ROUND(4000+500*(z.km_from_origin-a.km_from_origin),0)',
 'FROM route_stops a JOIN route_stops z ON z.route_id=a.route_id AND z.stop_order>a.stop_order',
 "JOIN routes r ON r.id=a.route_id WHERE r.code IN ('02-DI','02-VE','26-DI','26-VE','BRT01-DI','BRT01-VE')",
 'AND NOT EXISTS (SELECT 1 FROM fares f WHERE f.route_id=a.route_id AND f.from_station_id=a.station_id AND f.to_station_id=z.station_id);',
 '\n-- 14 days from the next Hanoi calendar day, 6 departures/day/direction.',
 '-- Dedicated simulated vehicle per route direction; 3-hour headway avoids overlaps.',
 "SET @hanoi_tomorrow=DATE(UTC_TIMESTAMP() + INTERVAL 7 HOUR) + INTERVAL 1 DAY;",
 'INSERT INTO schedules(route_id,departure_at,arrival_at,vehicle_code,capacity)',
 'WITH RECURSIVE days(n) AS (SELECT 0 UNION ALL SELECT n+1 FROM days WHERE n<13),',
 'hours(h) AS (SELECT 6 UNION ALL SELECT 9 UNION ALL SELECT 12 UNION ALL SELECT 15 UNION ALL SELECT 18 UNION ALL SELECT 21),',
 'departures AS (',
 " SELECT r.id route_id,CONCAT('DEMO-HN-',r.code) vehicle_code,IF(r.code LIKE 'BRT01%',90,60) capacity,",
 ' TIMESTAMP(@hanoi_tomorrow + INTERVAL days.n DAY) + INTERVAL hours.h HOUR - INTERVAL 7 HOUR dep,',
 ' (SELECT MAX(minutes_from_origin) FROM route_stops WHERE route_id=r.id) duration',
 ' FROM routes r CROSS JOIN days CROSS JOIN hours',
 " WHERE r.code IN ('02-DI','02-VE','26-DI','26-VE','BRT01-DI','BRT01-VE') AND r.status='ACTIVE'",
 ') SELECT route_id,dep,TIMESTAMPADD(MINUTE,duration,dep),vehicle_code,capacity FROM departures d',
 'WHERE NOT EXISTS (SELECT 1 FROM schedules s WHERE s.vehicle_code=d.vehicle_code AND s.departure_at=d.dep);',
 '\n-- Three illustrative tickets: two confirmed, one cancelled. One row = one passenger.',
 "SET @demo_schedule=(SELECT s.id FROM schedules s JOIN routes r ON r.id=s.route_id WHERE r.code='02-DI' AND s.status='SCHEDULED' AND s.departure_at>UTC_TIMESTAMP() ORDER BY s.departure_at LIMIT 1);",
]
for code,email,fromc,toc,name,phone,status in [
 ('DEMO-HN-0001','an@gobus.local','HN-BC','HN-PTIT','Nguyễn Văn An (demo)','0900000001','CONFIRMED'),
 ('DEMO-HN-0002','binh@gobus.local','HN-TT','HN-YN','Trần Thị Bình (demo)','0900000002','CONFIRMED'),
 ('DEMO-HN-0003','an@gobus.local','HN-NTS','HN-YN','Nguyễn Văn An (demo)','0900000001','CANCELLED')]:
    lines.extend([
     'INSERT INTO bookings(booking_code,user_id,schedule_id,from_station_id,to_station_id,contact_name,contact_phone,unit_price,status,booked_at,cancelled_at)',
     'SELECT '+quote(code)+',u.id,s.id,a.id,z.id,'+quote(name)+','+quote(phone)+',f.price,'+quote(status)+",UTC_TIMESTAMP(3),"+('UTC_TIMESTAMP(3)' if status=='CANCELLED' else 'NULL'),
     'FROM users u JOIN schedules s ON s.id=@demo_schedule JOIN stations a ON a.code='+quote(fromc)+' JOIN stations z ON z.code='+quote(toc),
     'JOIN fares f ON f.route_id=s.route_id AND f.from_station_id=a.id AND f.to_station_id=z.id',
     'WHERE u.email='+quote(email)+' AND NOT EXISTS (SELECT 1 FROM bookings WHERE booking_code='+quote(code)+');',
    ])
lines += ['COMMIT;','']
(root/'02-seed-hanoi.sql').write_text('\n'.join(lines),encoding='utf8')
print('Generated 02-seed-hanoi.sql: 19 stops, 6 directional routes, 40 route_stops, 130 fares, 504 schedules, 3 demo users and 3 demo tickets.')
